{{- if .Values.externalDatabase.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sealos-notify.fullname" . }}-external-database
  labels:
    {{- include "sealos-notify.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
