apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sealos-notify.fullname" . }}-api-auth
  labels:
    {{- include "sealos-notify.labels" . | nindent 4 }}
type: Opaque
stringData:
  apps.yaml: |
    apps:
      - appId: {{ .Values.auth.appId | quote }}
        appSecret: {{ .Values.auth.appSecret | quote }}
        name: {{ .Values.auth.appName | quote }}
        enabled: true
{{- if not .Values.externalDatabase.host }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sealos-notify.postgresql.fullname" . }}
  labels:
    {{- include "sealos-notify.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.username | quote }}
  password: {{ .Values.postgresql.password | quote }}
  database: {{ .Values.postgresql.database | quote }}
{{- end }}
