name: CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify modules
        run: go mod verify

      - name: Test
        run: go test -v -race -timeout 2m -count=1 ./...

      - name: Build
        run: go build ./...

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a
        with:
          version: v2.8.0
          args: --color=always --path-mode=abs
